### ISSUE TITLE
Add F-Droid button and links

### ISSUE THREAD

**Issue by Poussinou** [oversecio/oversec_website#2]
You could probably add the [button](https://fdroid.gitlab.io/artwork/badge/get-it-on.png) to get the app on F-Droid next to the one of Google Play :)

![image](https://user-images.githubusercontent.com/19646549/51072819-ad830c00-1667-11e9-8ef3-3f2671957063.png)

**Comment by oversecio** [comment]
Thanks, good point.

**Comment by oversecio** [comment]
Fixed https://github.com/oversecio/oversec_website/commit/34f9024872fd1888a041ac2fab898b5cf014dee8

**Comment by Poussinou** [comment]
Just to let you know, you are using the URL : `https://f-droid.org/en/packages/io.oversec.one/`


This one would probably be better : `https://f-droid.org/packages/io.oversec.one/`

Without the `en`, it allows people to directly have a translated description. For example I see in French if there is no `en` ;)

Just my two cents

**Comment by oversecio** [comment]
Good point, have changed it.
